name: Run Code Coverage

on: push

env:
  MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: SuperPassword

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Coverage
        id: coverage
        continue-on-error: true
        run: npm run coverage

      - name: Archive Test Result
        if: failure() || success()
        uses: actions/upload-artifact@v4
        with: 
          name: code-coverage-result
          path: coverage